#!/bin/bash
# This script is to check the output
# It should RETURN 0 if everything is successful, else bad

STUDENT_OUTPUT=$1

SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
REF_SOLUTION=${SCRIPT_DIR}/ref-sol.out

# Sanity check: Ensure files exist
if [[ ! -f ${STUDENT_OUTPUT} ]]; then
    echo "Student's output file is missing"
    exit 1
fi

if [[ ! -f ${REF_SOLUTION} ]]; then
    # If this happens... TA messed up something
    echo "Reference file is missing, please alert the head TA"
    exit 1
fi

# Run diff, but silence any output
diff ${STUDENT_OUTPUT} ${REF_SOLUTION} > /dev/null 2>&1

RET=$?
if [[ $RET -eq 0 ]]; then
    exit 0
else
    # If you want to allow students to debug what went wrong, can simply re-run diff here
    # Use -y for side-by-side diff
    diff -y ${STUDENT_OUTPUT} ${REF_SOLUTION}
    exit 1
fi

