#!/bin/bash
# This script checks the output (the path is provided as the first param)
# It should RETURN 0 if everything is successful, else bad
echo "CHECKING OUTPUT IN FILE $1"

NO_PACKETS_DROPPED=`cat $1 | grep "0% dropped"`

if [[ -n ${NO_PACKETS_DROPPED} ]]; then
    exit 0
else
    exit 1
fi

